version: '3.2'

services:

    app:
        container_name: foxhole-bot-app
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        depends_on:
            - database

    database:
        container_name: foxhole-bot-database
        image: mongo:latest
        restart: always
        ports:
            - 27001:27017
        volumes:
        - mongodb_data:/data/db
        environment:
            MONGO_INITDB_DATABASE: dfb
            MONGO_INITDB_ROOT_USERNAME: dfb
            MONGO_INITDB_ROOT_PASSWORD: dfb

volumes:
  mongodb_data: